### ISSUE TITLE
default timeout of 1s could be too short

### ISSUE THREAD

**Issue by aoberoi** [opentok/Opentok-Ruby-SDK#105]
referring to the work done in #78, it seems like some people are having issues with the 1s timeout.

its possible that the 1s is not just for TCP open, and many places in the world have ping times that are ~300ms so this shaves much of the headroom down.

@wobbals

**Comment by aoberoi** [comment]
cc @dramalho

**Comment by dramalho** [comment]
Maybe we can replace with `read_timeout` - and make the value configurable?

**Comment by dramalho** [comment]
in other news, Servers with 300ms lag times, ouch :/

**Comment by wobbals** [comment]
Yeah, I'm sure it's not the most common thing, but there are some quite-high times that we can see in worst-case on the global ping map: https://wondernetwork.com/pings

We've also seen occasional response time spikes in some of our API calls; same story - not a common thing but probably 1s is going to cut out access at times.

**Comment by dramalho** [comment]
so: 

* Replacing default_timeout with open_timeout (changes are if the OpenTok server accepted the  connection, it's going to - eventually - send out data)
* Maybe increase the 1s up a bit? 2, 4?

**Comment by teddythetwig** [comment]
Thanks for fixing this. We are in the EU region and on 1/10th of our calls we have been getting a Net::ReadTimeout since #78. Hope this gets merged today!

**Comment by aoberoi** [comment]
fixed in f958f48da0176043ee063dcbb11a3ae9021535a0

**Comment by jaysson** [comment]
We are having problems with 2 second timeout as well while developing. I think this should be configurable.

It works fine on server.
