### ISSUE TITLE
opentok.archives.all(options) does not support filtering by session ID

### ISSUE THREAD

**Issue by jeffswartz** [opentok/OpenTok-Ruby-SDK#126]
The OpenTok REST API now lets you filter by session ID when getting a list of archives: https://tokbox.com/developer/rest/#listing_archives. (You pass in a `sessionId` query parameter when calling the REST API method.) The `opentok.archives.all(options)` method in the OpenTok Ruby server SDK does not support this session ID filter.

**Comment by MrWilhelm** [comment]
`OpenTokAdapter.client.archives.all.select { |a| a.session_id == call.session_id }`

This can help temporarily.
