### ISSUE TITLE
Support of ruby 2.4.0

### ISSUE THREAD

**Issue by pinya** [opentok/OpenTok-Ruby-SDK#127]
Opentok gem v2.3.4 depends httparty (\~> 0.13.1), 
which depends on json (\~> 1.8),
which cannot build native extensions with ruby 2.4.0

**Comment by larsklevan** [comment]
Try upgrading to `json 1.8.6`. Worked for me.

**Comment by pinya** [comment]
Thank you, `json 1.8.6` works just fine
