### ISSUE TITLE
Adding 2 lines to the README

### ISSUE THREAD

**Issue by LucasCioffi** [opentok/Opentok-Ruby-SDK#13]
Thanks for a great gem!

I'd recommend updating the README to specify the following:
1. require 'opentok' should be added to the controller
2. the initializer code should go in something like opentok.rb

These clarifications would have saved me and probably some others some time.

**Comment by aoberoi** [comment]
Thanks for the suggestions, and kind words :smile:. Sorry that this issue has stuck around with no feedback for so long.

*  We now show the `require 'opentok'` in the README.
*  An initializer is a concern thats very specific to Rails, and this gem is trying to be more general than that.
