### ISSUE TITLE
Multiple instances of SDK with different API Keys

### ISSUE THREAD

**Issue by Fishz** [opentok/OpenTok-Ruby-SDK#135]
Hello!

Stumbled upon an issue where if two (or more) instances of the `OpenTok` class are created with different `api_key`s set, requests from any instance use the `api_key` from the latest-instantiated object.

To reproduce, try out this snippet which instantiates two objects with different credentials (example credentials spoofed) and switches creating sessions between the two:

```
OTSDK     = OpenTok::OpenTok.new("1234", "1234")
OTSDK_TWO = OpenTok::OpenTok.new("9999", "9999")

def decode_opentok_session_id(tok)
  Base64.urlsafe_decode64(tok[2..tok.length])
end

sessions = []
5.times do |i|
  if i % 2 != 0
    session = OTSDK.create_session
  else
    session = OTSDK_TWO.create_session
  end

  sessions << session
end

sessions.each { |s| puts s.api_key }

sessions.each do |sesh|
  puts decode_opentok_session_id(sesh.session_id)
end
```

The output would be along the lines of:

```
1234
9999
1234
9999
1234

1~1234~xyz...
1~9999~zyx...
1~9999~zyx...
1~9999~zyx...
1~9999~zyx...
```

As you can see, the session objects returned have the correct `api_key` but the `session_id` from the actual API response doesn't -- this can/will result in the dreaded "API key-session mismatch" when generating a token.

At any rate, this is resolved in the latest (unreleased) version of the gem but is present in `2.3.4`; I believe the issue lives in `client.rb` where the `headers` value is a class-variable rather than an instance variable. Since the latest code uses the instance's `api_key` variable when generating headers, it's no longer present. Given it's resolved (and we've found a workaround) I don't think a PR is necessary. Thanks for fixing in the latest version!

**Comment by aiham** [comment]
@Fishz No problem. We'll try to get this released as soon as we can.
