### ISSUE TITLE
httparty dependency is out of date and forces gem downgrades

### ISSUE THREAD

**Issue by cainlevy** [opentok/OpenTok-Ruby-SDK#139]
The httparty dependency is locked to 0.13.x, which is about [10 months out of date](https://github.com/jnunemaker/httparty/releases/tag/v0.14.0) and is missing numerous [improvements and fixes](https://github.com/jnunemaker/httparty/blob/master/Changelog.md).

We noticed because adding `gem 'opentok'` forced Bundler to downgrade to `json@1.8`. httparty fixed this in v0.14 by [removing the json dependency entirely](https://github.com/jnunemaker/httparty/commit/37dfb42382e4365fb79d0323cd531198121cfb81).

If a specific version of httparty is necessary, please consider updating to a newer dependency. Alternately, if httparty is convenient but not necessary, please consider [removing the dependency](http://www.mikeperham.com/2016/02/09/kill-your-dependencies/) altogether.

**Comment by aiham** [comment]
@cainlevy Thanks for the report. I'll take a look at this. CC @Lucashuang0802

**Comment by aiham** [comment]
Fixed in #137, thanks @cainlevy and @Lucashuang0802
