### ISSUE TITLE
Archive filename

### ISSUE THREAD

**Issue by estebanz01** [opentok/OpenTok-Ruby-SDK#154]
Hey everyone!

I saw this property: https://github.com/opentok/OpenTok-Ruby-SDK/blob/master/lib/opentok/archives.rb#L29 and I was trying to use it to create, in my S3 bucket, a recording with that name, but not success so far. I also noticed that if I use the tokbox archive storage option, it uses the name I specify.

Do you know how can I setup the name of the combined file in my S3 bucket using this property?

Thanks!

**Comment by aiham** [comment]
Hi @estebanz01 

I don't believe you can customise the filename as it states here: https://tokbox.com/developer/rest/#setting-an-amazon-s3-or-windows-azure-archiving-upload-target

> If you set an upload target, each completed archive file is uploaded as a file named archive.mp4 in the path /projectKey/archiveId/ of the target bucket, where projectKey is the project API key, and archiveId is the archive ID.

What do you mean when you say "use the tokbox archive storage option"? Are you referring to setting an archive upload target in your TokBox account?

**Comment by estebanz01** [comment]
Hi @aiham I'm refering to the Tokbox S3 bucket that is used when we don't setup an azure/S3 bucket account.

If I do not configure an storage option, I see the following in the Tokbox console, which is a name I specified via `Archive.name` property:
![test](https://user-images.githubusercontent.com/2417465/34722433-e76223b8-f514-11e7-914e-13f663f2271b.png)

so, It's not possible to have the same behaviour in my Azure/S3 bucket ?

**Comment by marcioaffonso** [comment]
@estebanz01, all the archives when saved to your azure bucket have its name structured as API_KEY/ARCHIVE_ID/archive.mp4 as referenced in https://tokbox.com/developer/guides/archiving/using-azure.html.

The name property only applies to archives saved in the OpenTok bucket.

Please use https://support.tokbox.com or support@tokbox.com if you have any questions or issues related to the OpenTok platform. The repository issues should only be used to issues with the code itself.
