### ISSUE TITLE
RuntimeError (Expire time must be within the next 30 days)

### ISSUE THREAD

**Issue by sasikiran** [opentok/OpenTok-Ruby-SDK#159]
I am using ``opentok 3.0.1``.  I using the following statement to generate a token with a 3 hour expiry time:

``
token = session.generate_token(expire_time: Time.now.to_i + (3 * 60 * 60))
``

The code worked for us all these days, except it started producing the runtime error since yesterday. The rails app is hosted on Heroku.

Please advise whether this is a bug in the SDK.

Thanks.

**Comment by msach22** [comment]
@sasikiran Hmm, I just ran the same code and I'm not seeing the expire time error. Is this still happening for you?

**Comment by msach22** [comment]
@sasikiran I'm closing this issue, please re-open if you're still seeing this.
