### ISSUE TITLE
Using "Automatic Archives" No way to retrieve archive with SessionID

### ISSUE THREAD

**Issue by Johnsalzarulo** [opentok/OpenTok-Ruby-SDK#169]
I've been scouring documentation and trying to solve this specific use case: 

- Session token is created with the `archive_mode` set to `always`
- Session takes place and archive is created automatically. 
- Now - I need to be able to access a **specific archive** from the list of archives. 
- The only way to do this is to pull down the whole list and parse the JSON. 
- It would be a really nice feature to be able to do something like: 

````
    archive = opentok.archives.find_by_session(session_id)
````

I'd love to build it / submit a PR - just making sure this functionality doesn't already exist - maybe I'm missing something. 

Thanks!

**Comment by msach22** [comment]
@Johnsalzarulo This functionality exists, but is not documented. We will update the docs in the very near future 😄

**Comment by Johnsalzarulo** [comment]
Thanks @msach22 !
