### ISSUE TITLE
Update JWT dependency to ~> 2.0?

### ISSUE THREAD

**Issue by stefanrendevski** [opentok/OpenTok-Ruby-SDK#182]
Is there a specific reason why this gem has jwt dependency locked to ~> 1.5.6? I am using a JWT authentication library that is dependent on jwt 2.1, so when I try to install this gem, bundler is complaining because of the version mismatch. I am considering forking the gem in order to update the dependency, but I was wondering if anyone is aware of any issues with jwt 2.1.

**Comment by nvtin** [comment]
Same to me. I am using devise-jwt gem. So it depends on jwt 2.1 but opentok depends on jwt 1.5.6. 
What should I do? or anyone take care of it?

**Comment by stefanrendevski** [comment]
@nvtin I made a fork with an updated dependency, and all the current tests are passing. So i assume you can safely fork it and update. I haven't submitted a pull request yet, because maybe the authors want to keep the jwt version for some specific reason.

**Comment by nvtin** [comment]
Thanks @stefanrendevski  
Forking it is a good choice for now, but it is not recommended.
I dont know why nobody answer this issue. Our company is going to pay $2k/month to use this tokbox if I can integrate it successfully. They should support this issue soon.

**Comment by msach22** [comment]
@stefanrendevski There's no reason to keep the JWT library at 1.5.6, please go ahead and submit a PR and I'd be happy to check it out 😄

**Comment by AnilRh** [comment]
Still open, huh?

**Comment by hmesander** [comment]
Is there any update on this issue?  It is holding us back from updating a devise module that we need.

**Comment by AnilRh** [comment]
No commits in over a year - is the Ruby SDK officially dead? :(

**Comment by jimedelstein** [comment]
@msach22 it's been over a year with no update, looks like the same is true for the repo in general.  Safe to assume that Nexmo/Tokbox is no longer maintaining the Ruby SDK?

**Comment by msach22** [comment]
Hi Team, we've just merged in: https://github.com/opentok/OpenTok-Ruby-SDK/pull/192

This should resolve the issues going forward. I'll comment and update the issue once the changes are released.

**Comment by jeffswartz** [comment]
We have released v4.0.0, which fixes this issue.
