### ISSUE TITLE
OpenTok::OpenTokError: Failed to connect to OpenTok. Response code: Authentication failed while creating a session.

### ISSUE THREAD

**Issue by motoku** [opentok/OpenTok-Ruby-SDK#185]
**OpenTok::OpenTokError: Failed to connect to OpenTok. Response code: Authentication failed while creating a session.**

Getting this error since February when trying to connect from the localhost.

Everything works just fine on the production server with the same credentials.

ruby 2.3.3p222
gem version "~> 3.1.0"

Please help

**Comment by motoku** [comment]
I found a solution thanks to my googling skills but that was really-really hard.

"However, we've seen this issue in the past where the server clocks are out of sync and the JWT token is expiring too soon. To fix the clock issue, please check out the following resources that have resolved issues in the past"

3 minutes time difference on my laptop caused this and there were no chance to understand why is this happening.

My suggestion here is to add some kind of an error description for this particular edge case.

Thanks!

**Comment by 007kishore** [comment]
Please provide the resources that you have followed to solve the issue.
I am facing a similar kind of issue where the session is getting created while initiating the video chat.

Thnaks.

**Comment by masudhossain** [comment]
BUMP. Getting this error in 2020.

**Comment by choosen** [comment]
I had same problem. 
I coppied wrong API keys and secrets. 

They are different credentials for :

1. OpenTok REST API
2. Project API for creating sessions and tokens
