### ISSUE TITLE
Change SHA1 to more modern hash algorithm in token generators

### ISSUE THREAD

**Issue by choosen** [opentok/OpenTok-Ruby-SDK#202]
TokenGenerator uses outdated SHA1
https://github.com/opentok/OpenTok-Ruby-SDK/blob/f618f8a30ba0958d0920ed35ec0f974de80b9e81/lib/opentok/token_generator.rb#L93
SHA1 is not secure enough those days.

You should switch to SHA2-256 or SHA3 to be more secure. 
Ofc it will change also servers code, but it can be achieved by adding `hash_algorithm: SHA3` to options in token generator

**Comment by benhayehudi** [comment]
Thank you, @choosen, for raising this. We are working on updating all of our OpenTok SDKs and we will certainly look into this as well. Appreciate it!

**Comment by choosen** [comment]
OpenTok use sha1 @ `OpenSSL::HMAC`   so it seems not so bad as I thought ; )
