### ISSUE TITLE
How can we implement remote mouse control of the other participant (much like how zoom works) ?

### ISSUE THREAD

**Issue by kamalpandey** [opentok/OpenTok-Ruby-SDK#208]

**Comment by benhayehudi** [comment]
Hi Kamal,

Good to hear from you again. As I addressed in a comment on the [DEV blog post](https://dev.to/benhayehudi/comment/p5c7) where you first raised this, unfortunately, this is not possible currently within the constraints of the technology. 

All the best,

Ben
