### ISSUE TITLE
Failed to connect to OpenTok. Response code: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by riwaj-shrestha-iw** [opentok/OpenTok-Ruby-SDK#221]
![image](https://user-images.githubusercontent.com/64764984/87756586-e71e6f80-c828-11ea-9c15-72a63827491d.png)
Everything is working fine in my friend's computer. Got this error after setting up project in new device.
Please Help
Gem version : 3.0.8
Rails version: 5.1.4
Ruby : 2.5.8

**Comment by bencgreenberg** [comment]
Hey there @riwaj-shrestha-iw, 

When you inspect `@opentok` what are the values there? Is it a properly instantiated instance of an OpenTok client, with your API credentials?

Also, could you try upgrading the gem, you're running on a bit of an older version. The current version is `4.1.2`.
