### ISSUE TITLE
Misleading / wrong comments about archive duration

### ISSUE THREAD

**Issue by Bartuz** [opentok/OpenTok-Ruby-SDK#222]
Hello,

I'm using gem `opentok 4.1.0`.  [Code documentation](https://github.com/opentok/OpenTok-Ruby-SDK/blame/master/lib/opentok/archive.rb#L9-L11) mentions given time is in milliseconds and is string.

Retrieving archive with `opentok.archives.all({ sessionId: session_id }).first.duration` gives me integer which represents seconds, not milliseconds. This would make sense, as [your API docs states](https://tokbox.com/developer/guides/archiving/) it is indeed integer and seconds (and this library is just reading json, isn't it?)

**Comment by bencgreenberg** [comment]
Thanks, @Bartuz for raising this issue. I will take a look at it early next week to make sure our code documentation conforms more accurately to the behavior of the API.
