### ISSUE TITLE
Ruby 2.2.0 / Rails 4.2 issue

### ISSUE THREAD

**Issue by superacidjax** [opentok/OpenTok-Ruby-SDK#79]
It seems that with the OT 2.2.3 gem, the following error happens when attempting to run rake (or any rails command)

``` shell
rake aborted!
LoadError: cannot load such file -- digest/hmac
```

I haven't been able to isolate the issue within the gem, but I have isolated it to the gem itself.

**Comment by aoberoi** [comment]
@superacidjax thanks for reporting. it looks like the Ruby 2.2.0 stdlib has removed the `Digest::HMAC` class, and suggests to use `OpenSSL::HMAC` instead ([source](http://ruby-doc.org/stdlib-2.1.0/libdoc/digest/rdoc/Digest/HMAC.html)).

    "CAUTION: Use of this library is discouraged, because this implementation was meant to be
    experimental but somehow got into the 1.9 series without being noticed. Please use OpenSSL::HMAC
    in the “openssl” library instead."

the class is only used in 2 places, so it should be a pretty quick fix. willing to accept a PR for this :)

**Comment by superacidjax** [comment]
I'll PR tomorrow. I wanted to be sure that there wasn't some breaking reason for the original library. Thanks!
