### ISSUE TITLE
Documentation links out of date

### ISSUE THREAD

**Issue by shekibobo** [opentok/Opentok-Ruby-SDK#9]
In `open_tok_sdk.rb`
- [x] [Token Creation](https://github.com/opentok/Opentok-Ruby-SDK/blob/master/lib/open_tok/open_tok_sdk.rb#L54)
- [x] [Session Creation](https://github.com/opentok/Opentok-Ruby-SDK/blob/master/lib/open_tok/open_tok_sdk.rb#L122)

These are probably supposed to link to [Server Side Docs for Ruby SDK](http://www.tokbox.com/opentok/docs/server/server_side_libraries.html?proglang=ruby), but there may be a better match somewhere else.

**Comment by aoberoi** [comment]
thanks for commenting, and sorry this issue has remained open for so long without feedback.

both of these are now covered quite well in the README.
