### ISSUE TITLE
can multiple users try out the Hello World?

### ISSUE THREAD

**Issue by jjb** [opentok/Opentok-Ruby-SDK#94]
In the Hello World app, a session is created whenever the page is loaded. How then can two users access the same session?

(sorry if I'm missing something obvious!)

**Comment by aoberoi** [comment]
Actually they `create_session()` method is only called once on startup, and the result is stored in the `app.settings`. This means you should get the same session on two different page loads. But also notice that a different `token` is generated for each page load.

If you're experiencing something different, do let us know.

**Comment by jjb** [comment]
Since I asked my question I've become more familiar with the system -- basically I didn't understand when/how multiple participants are included in the DOM -- the answer is

```js
document.getElementById('subscribers').appendChild(subContainer)
```

**Comment by aoberoi** [comment]
@jjb glad you figured that out, and sorry my comment wasn't more helpful!
